// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XeniaDiscord.Data;

#nullable disable

namespace XeniaDiscord.Data.Migrations
{
    [DbContext(typeof(XeniaDbContext))]
    partial class XeniaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XeniaDiscord.Data.Models.BanSync.BanSyncGuildModel", b =>
                {
                    b.Property<string>("GuildId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("LogChannelId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.HasIndex("GuildId", "State", "Enable");

                    b.ToTable("BanSyncGuilds", (string)null);
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.BanSync.BanSyncGuildSnapshotModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "GuildId")
                        .IsDescending();

                    b.ToTable("BanSyncGuildSnapshots", (string)null);
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.BanSync.BanSyncRecordModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Ghost")
                        .HasColumnType("boolean");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("GuildId", "Ghost")
                        .IsDescending();

                    b.HasIndex("UserId", "Ghost")
                        .IsDescending();

                    b.ToTable("BanSyncRecords", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
