// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XeniaDiscord.Data;

#nullable disable

namespace XeniaDiscord.Data.Migrations
{
    [DbContext(typeof(XeniaDbContext))]
    partial class XeniaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BanSyncRecordModelGuildMemberCacheModel", b =>
                {
                    b.Property<Guid>("RelatedBanSyncRecordsId")
                        .HasColumnType("uuid");

                    b.Property<string>("CachedGuildMembersByUserGuildId")
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CachedGuildMembersByUserUserId")
                        .HasColumnType("character varying(40)");

                    b.HasKey("RelatedBanSyncRecordsId", "CachedGuildMembersByUserGuildId", "CachedGuildMembersByUserUserId");

                    b.HasIndex("CachedGuildMembersByUserGuildId", "CachedGuildMembersByUserUserId");

                    b.ToTable("BanSyncRecordModelGuildMemberCacheModel");
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.BanSync.BanSyncGuildModel", b =>
                {
                    b.Property<string>("GuildId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("LogChannelId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.HasIndex("GuildId", "State", "Enable");

                    b.ToTable("BanSyncGuilds", (string)null);
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.BanSync.BanSyncGuildSnapshotModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("LogChannelId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "GuildId")
                        .IsDescending();

                    b.ToTable("BanSyncGuildSnapshots", (string)null);
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.BanSync.BanSyncRecordModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditLogBanEntryId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("BannedByUserId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Ghost")
                        .HasColumnType("boolean");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserPartialSnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("UserPartialSnapshotId");

                    b.HasIndex("GuildId", "Ghost")
                        .IsDescending();

                    b.HasIndex("GuildId", "UserId");

                    b.HasIndex("UserId", "Ghost")
                        .IsDescending();

                    b.ToTable("BanSyncRecords", (string)null);
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.Cache.AuditLogBanCacheModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("JsonData")
                        .HasColumnType("text");

                    b.Property<string>("JsonDataType")
                        .HasColumnType("text");

                    b.Property<string>("PerformedByUserId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetUserId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Id", "GuildId", "CreatedAt", "Action");

                    b.HasIndex("Id", "GuildId", "CreatedAt", "Action", "PerformedByUserId");

                    b.ToTable("Cache_AuditLogEntry_Ban", (string)null);
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.Cache.GuildCacheModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscoverySplashUrl")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("RecordCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SplashUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cache_Guild", (string)null);
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.Cache.GuildMemberCacheModel", b =>
                {
                    b.Property<string>("GuildId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("UserId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("FirstJoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMember")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebhook")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "UserId");

                    b.HasIndex("GuildId", "UserId", "IsMember");

                    b.ToTable("Cache_GuildMember", (string)null);
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.Cache.UserCacheModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .HasColumnType("text");

                    b.Property<string>("DisplayAvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("GlobalName")
                        .HasColumnType("text");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebhook")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RecordCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cache_User", (string)null);
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.PartialSnapshot.GuildPartialSnapshotModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "GuildId")
                        .IsDescending();

                    b.ToTable("GuildPartialSnapshot", (string)null);
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.PartialSnapshot.UserPartialSnapshotModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "UserId")
                        .IsDescending();

                    b.ToTable("UserPartialSnapshot", (string)null);
                });

            modelBuilder.Entity("BanSyncRecordModelGuildMemberCacheModel", b =>
                {
                    b.HasOne("XeniaDiscord.Data.Models.BanSync.BanSyncRecordModel", null)
                        .WithMany()
                        .HasForeignKey("RelatedBanSyncRecordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XeniaDiscord.Data.Models.Cache.GuildMemberCacheModel", null)
                        .WithMany()
                        .HasForeignKey("CachedGuildMembersByUserGuildId", "CachedGuildMembersByUserUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.BanSync.BanSyncRecordModel", b =>
                {
                    b.HasOne("XeniaDiscord.Data.Models.BanSync.BanSyncGuildModel", "BanSyncGuild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XeniaDiscord.Data.Models.PartialSnapshot.UserPartialSnapshotModel", "UserPartialSnapshot")
                        .WithMany()
                        .HasForeignKey("UserPartialSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XeniaDiscord.Data.Models.Cache.GuildMemberCacheModel", "CachedGuildMember")
                        .WithMany()
                        .HasForeignKey("GuildId", "UserId")
                        .HasAnnotation("Custom:IsConstrained", false);

                    b.Navigation("BanSyncGuild");

                    b.Navigation("CachedGuildMember");

                    b.Navigation("UserPartialSnapshot");
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.Cache.GuildMemberCacheModel", b =>
                {
                    b.HasOne("XeniaDiscord.Data.Models.Cache.GuildCacheModel", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("XeniaDiscord.Data.Models.Cache.GuildCacheModel", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
